formatVersion: 1
formatType: am-configuration
---
# installations will go into the standard /opt/am hierarchy

applications:
  installedAppsManifestDir: "/opt/am/manifests"
  appImageMountDir: "/opt/am/image-mounts"
  database: "/opt/am/apps.db"

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/opt/am/apps"
  documentPath: "/opt/am/docs"
  mountPoint: "/opt"
  isDefault: true

- id: "removable-0"
  installationPath: "/media/sdcard/apps"
  documentPath: "/media/sdcard/docs"
  mountPoint: "/media/sdcard"
