formatVersion: 1
formatType: am-configuration
---
# installations will go into the standard /opt/am hierarchy

applications:
  installedAppsManifestDir: "/opt/am/manifests"
  appImageMountDir: "/opt/am/image-mounts"
  database: "/opt/am/apps.db"

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/opt/am/apps"
  documentPath: "/opt/am/docs"
  mountPoint: "/opt"
  isDefault: true

- id: "removable-0"
  installationPath: "/media/sdcard/apps"
  documentPath: "/media/sdcard/docs"
  mountPoint: "/media/sdcard"

# useful debug wrappers - mainly for Unix
# %program% and %arguments% are internal variables

debugWrappers:
- name: gdbserver
  command: [ '/usr/bin/gdbserver', ':%port%', '%program%', '%arguments%' ]
  parameters:  # <name>: <default value>
    port: 5555
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: qmldebugger # can also be used for the qmlprofiler
  command: ['%program%', '-qmljsdebugger=port:%port%,block', '%arguments%' ]
  parameters:  # <name>: <default value>
    port: 3456
  supportedRuntimes: [ qml ]
  supportedContainers: [ process ]
- name: cppqmldebugger
  command: [ '/usr/bin/gdbserver', ':%gdbport%', '%program%', '-qmljsdebugger=port:%qmlport%,block', '%arguments%' ]
  parameters:  # <name>: <default value>
    gdbport: 5555
    qmlport: 3456
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: valgrind
  command: [ '/usr/bin/valgrind', '%program%', '%arguments%' ]
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: strace
  command: [ '/usr/bin/strace', '%program%', '%arguments%' ]
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
